[package]
name = "peelbox-wolfi"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow = "1.0"
reqwest = { version = "0.12.25", features = ["blocking"] }
flate2 = "1.0"
tar = "0.4"
dirs = "6.0.0"
bincode = "1.3.3"

[dev-dependencies]
