[profile.default]
slow-timeout = { period = "300s", terminate-after = 3 }

[profile.ci.junit]
path = "junit.xml"

[test-groups]
serial-tests = { max-threads = 1 }
container-tests = { max-threads = 2 }

[[profile.default.overrides]]
filter = 'test(container_) | test(e2e) | binary(container_e2e) | binary(static_e2e) | test(llm_) | binary(llm_e2e) | binary(llm_embedded)'
test-group = 'container-tests'

[[profile.default.overrides]]
filter = 'binary(container_buildkit)'
test-group = 'serial-tests'
